default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB_DEV_NAME'] %>


test:
  <<: *default
  database: <%= ENV['POSTGRES_DB_TEST_NAME'] %>